
export const vocabData = {
    HSK1: [
      { 
        unit: 1, 
        words: [
          { character: '你好', pinyin: 'nǐ hǎo', meaning: 'Hello' },
          { character: '谢谢', pinyin: 'xiè xiè', meaning: 'Thank you' },
          { character: '再见', pinyin: 'zài jiàn', meaning: 'Goodbye' },
          { character: '是', pinyin: 'shì', meaning: 'To be' },
          { character: '不', pinyin: 'bù', meaning: 'Not' },
        ] 
      },
      { 
        unit: 2, 
        words: [
          { character: '我', pinyin: 'wǒ', meaning: 'I, me' },
          { character: '你', pinyin: 'nǐ', meaning: 'You' },
          { character: '他', pinyin: 'tā', meaning: 'He, him' },
          { character: '她', pinyin: 'tā', meaning: 'She, her' },
          { character: '我们', pinyin: 'wǒ men', meaning: 'We, us' },
        ] 
      },
      { 
        unit: 3, 
        words: [
          { character: '家', pinyin: 'jiā', meaning: 'Home, family' },
          { character: '朋友', pinyin: 'péng yǒu', meaning: 'Friend' },
          { character: '学校', pinyin: 'xué xiào', meaning: 'School' },
          { character: '老师', pinyin: 'lǎo shī', meaning: 'Teacher' },
          { character: '学生', pinyin: 'xué shēng', meaning: 'Student' },
        ] 
      },
    ],
    HSK2: [
      { 
        unit: 1, 
        words: [
          { character: '天气', pinyin: 'tiān qì', meaning: 'Weather' },
          { character: '非常', pinyin: 'fēi cháng', meaning: 'Very, extremely' },
          { character: '踢足球', pinyin: 'tī zú qiú', meaning: 'Play soccer' },
          { character: '早上', pinyin: 'zǎo shàng', meaning: 'Morning' },
          { character: '起床', pinyin: 'qǐ chuáng', meaning: 'Get up' },
        ] 
      },
      { 
        unit: 2, 
        words: [
          { character: '衣服', pinyin: 'yī fú', meaning: 'Clothes' },
          { character: '颜色', pinyin: 'yán sè', meaning: 'Color' },
          { character: '便宜', pinyin: 'pián yí', meaning: 'Cheap' },
          { character: '贵', pinyin: 'guì', meaning: 'Expensive' },
          { character: '商店', pinyin: 'shāng diàn', meaning: 'Store' },
        ] 
      },
      { 
        unit: 3, 
        words: [
          { character: '手机', pinyin: 'shǒu jī', meaning: 'Mobile phone' },
          { character: '电脑', pinyin: 'diàn nǎo', meaning: 'Computer' },
          { character: '聊天', pinyin: 'liáo tiān', meaning: 'Chat' },
          { character: '上网', pinyin: 'shàng wǎng', meaning: 'Surf the internet' },
          { character: '音乐', pinyin: 'yīn yuè', meaning: 'Music' },
        ] 
      },
    ],
    HSK3: [
      { 
        unit: 1, 
        words: [
          { character: '旅游', pinyin: 'lǚ yóu', meaning: 'Travel' },
          { character: '地铁', pinyin: 'dì tiě', meaning: 'Subway' },
          { character: '飞机', pinyin: 'fēi jī', meaning: 'Airplane' },
          { character: '车站', pinyin: 'chē zhàn', meaning: 'Station' },
          { character: '地图', pinyin: 'dì tú', meaning: 'Map' },
        ] 
      },
      { 
        unit: 2, 
        words: [
          { character: '医生', pinyin: 'yī shēng', meaning: 'Doctor' },
          { character: '医院', pinyin: 'yī yuàn', meaning: 'Hospital' },
          { character: '感冒', pinyin: 'gǎn mào', meaning: 'Catch a cold' },
          { character: '药', pinyin: 'yào', meaning: 'Medicine' },
          { character: '健康', pinyin: 'jiàn kāng', meaning: 'Health' },
        ] 
      },
      { 
        unit: 3, 
        words: [
          { character: '考试', pinyin: 'kǎo shì', meaning: 'Exam' },
          { character: '成绩', pinyin: 'chéng jì', meaning: 'Grade, score' },
          { character: '练习', pinyin: 'liàn xí', meaning: 'Practice' },
          { character: '问题', pinyin: 'wèn tí', meaning: 'Question' },
          { character: '回答', pinyin: 'huí dá', meaning: 'Answer' },
        ] 
      },
    ],
    
    HSK4: [
      {
        unit: 1,
        words: [
          { character: '爱情', pinyin: 'àiqíng', partOfSpeech: 'n.', meaning: 'love (between a man and a woman)' },
          { character: '不仅', pinyin: 'bùjǐn', partOfSpeech: 'conj.', meaning: 'not only' },
          { character: '从来', pinyin: 'cónglái', partOfSpeech: 'adv.', meaning: 'always, all along' },
          { character: '法律', pinyin: 'fǎlǜ', partOfSpeech: 'n.', meaning: 'law' },
          { character: '感动', pinyin: 'gǎndòng', partOfSpeech: 'v.', meaning: 'to touch, to move' },
          { character: '刚', pinyin: 'gāng', partOfSpeech: 'adv.', meaning: 'just, not long' },
          { character: '共同', pinyin: 'gòngtóng', partOfSpeech: 'adj.', meaning: 'common, shared' },
          { character: '够', pinyin: 'gòu', partOfSpeech: 'v.', meaning: 'to be enough' },
          { character: '互相', pinyin: 'hùxiāng', partOfSpeech: 'adv.', meaning: 'mutually' },
          { character: '即使', pinyin: 'jíshǐ', partOfSpeech: 'conj.', meaning: 'even if' },
          { character: '加班', pinyin: 'jiā bān', partOfSpeech: 'v.', meaning: 'to work overtime' },
          { character: '接受', pinyin: 'jiēshòu', partOfSpeech: 'v.', meaning: 'to accept' },
          { character: '开玩笑', pinyin: 'kāi wánxiào', partOfSpeech: 'v.', meaning: 'to be kidding' },
          { character: '浪漫', pinyin: 'làngmàn', partOfSpeech: 'adj.', meaning: 'romantic' },
          { character: '两', pinyin: 'liǎ', partOfSpeech: 'num.-m.', meaning: 'two, both' },
          { character: '脾气', pinyin: 'píqi', partOfSpeech: 'n.', meaning: 'temper, disposition' },
          { character: '缺点', pinyin: 'quēdiǎn', partOfSpeech: 'n.', meaning: 'shortcoming' },
          { character: '深', pinyin: 'shēn', partOfSpeech: 'adj.', meaning: 'deep' },
          { character: '生活', pinyin: 'shēnghuó', partOfSpeech: 'n./v.', meaning: 'life; to live' },
          { character: '适合', pinyin: 'shìhé', partOfSpeech: 'v.', meaning: 'to suit, to fit' },
          { character: '首先', pinyin: 'shǒuxiān', partOfSpeech: 'pron.', meaning: 'first' },
          { character: '熟悉', pinyin: 'shúxī', partOfSpeech: 'v.', meaning: 'to be familiar with' },
          { character: '吸引', pinyin: 'xīyǐn', partOfSpeech: 'v.', meaning: 'to attract' },
          { character: '羡慕', pinyin: 'xiànmù', partOfSpeech: 'v.', meaning: 'to envy, to admire' },
          { character: '幸福', pinyin: 'xìngfú', partOfSpeech: 'adj.', meaning: 'happy' },
          { character: '性格', pinyin: 'xìnggé', partOfSpeech: 'n.', meaning: 'character, personality' },
          { character: '印象', pinyin: 'yìnxiàng', partOfSpeech: 'n.', meaning: 'impression' },
          { character: '幽默', pinyin: 'yōumò', partOfSpeech: 'adj.', meaning: 'humorous' },
          { character: '原因', pinyin: 'yuányīn', partOfSpeech: 'n.', meaning: 'reason' },
          { character: '自然', pinyin: 'zìrán', partOfSpeech: 'adv.', meaning: 'naturally, certainly' },
          { character: '最好', pinyin: 'zuìhǎo', partOfSpeech: 'adv.', meaning: 'had better' },
        ],
      }
      ,{
        unit: 2,
        words: [
          { character: '毕业', pinyin: 'bì yè', partOfSpeech: 'v.', meaning: 'to graduate' },
          { character: '差不多', pinyin: 'chàbùduō', partOfSpeech: 'adv.', meaning: 'almost' },
          { character: '重新', pinyin: 'chóngxīn', partOfSpeech: 'adv.', meaning: 'again, once more' },
          { character: '当', pinyin: 'dāng', partOfSpeech: 'prep.', meaning: 'when, just at (a time or place)' },
          { character: '短信', pinyin: 'duǎnxìn', partOfSpeech: 'n.', meaning: 'text message' },
          { character: '而', pinyin: 'ér', partOfSpeech: 'conj.', meaning: '(showing a contrast) while, yet' },
          { character: '丰富', pinyin: 'fēngfù', partOfSpeech: 'v.', meaning: 'to enrich' },
          { character: '逛', pinyin: 'guàng', partOfSpeech: 'v.', meaning: 'to stroll, to roam' },
          { character: '好像', pinyin: 'hǎoxiàng', partOfSpeech: 'adv.', meaning: 'as if' },
          { character: '及时', pinyin: 'jíshí', partOfSpeech: 'adv.', meaning: 'in time' },
          { character: '交流', pinyin: 'jiāoliú', partOfSpeech: 'v.', meaning: 'to exchange, to communicate' },
          { character: '交朋友', pinyin: 'jiāo péngyǒu', partOfSpeech: 'v.', meaning: 'to make (friends)' },
          { character: '尽管', pinyin: 'jǐnguǎn', partOfSpeech: 'conj.', meaning: 'although' },
          { character: '镜子', pinyin: 'jìngzi', partOfSpeech: 'n.', meaning: 'mirror' },
          { character: '聚会', pinyin: 'jùhuì', partOfSpeech: 'v./n.', meaning: 'to have a party; party, get-together' },
          { character: '困难', pinyin: 'kùnnan', partOfSpeech: 'n.', meaning: 'difficulty' },
          { character: '理解', pinyin: 'lǐjiě', partOfSpeech: 'v.', meaning: 'to understand' },
          { character: '联系', pinyin: 'liánxì', partOfSpeech: 'v.', meaning: 'to contact' },
          { character: '麻烦', pinyin: 'máfan', partOfSpeech: 'v.', meaning: 'to bother' },
          { character: '陪', pinyin: 'péi', partOfSpeech: 'v.', meaning: 'to accompany' },
          { character: '平时', pinyin: 'píngshí', partOfSpeech: 'n.', meaning: 'normal times' },
          { character: '却', pinyin: 'què', partOfSpeech: 'adv.', meaning: 'but, yet' },
          { character: '适应', pinyin: 'shìyìng', partOfSpeech: 'v.', meaning: 'to get used to' },
          { character: '讨厌', pinyin: 'tǎoyàn', partOfSpeech: 'v.', meaning: 'to dislike' },
          { character: '无聊', pinyin: 'wúliáo', partOfSpeech: 'adj.', meaning: 'boring' },
          { character: '友谊', pinyin: 'yǒuyì', partOfSpeech: 'n.', meaning: 'friendship' },
          { character: '真正', pinyin: 'zhēnzhèng', partOfSpeech: 'adj.', meaning: 'true, real' },
          { character: '正好', pinyin: 'zhènghǎo', partOfSpeech: 'adv.', meaning: 'just in time, just right' },
          { character: '周围', pinyin: 'zhōuwéi', partOfSpeech: 'n.', meaning: 'surrounding' },
          { character: '专门', pinyin: 'zhuānmén', partOfSpeech: 'adv.', meaning: 'specially' },
        ],
      }
      ,
      {
        unit: 3,
        words: [
          { character: '安排', pinyin: 'ānpái', partOfSpeech: 'v.', meaning: 'to arrange' },
          { character: '本来', pinyin: 'běnlái', partOfSpeech: 'adv.', meaning: 'originally, at first' },
          { character: '不管', pinyin: 'bùguǎn', partOfSpeech: 'conj.', meaning: 'no matter (what, how, etc.)' },
          { character: '材料', pinyin: 'cáiliào', partOfSpeech: 'n.', meaning: 'data, material' },
          { character: '诚实', pinyin: 'chéngshí', partOfSpeech: 'adj.', meaning: 'honest' },
          { character: '符合', pinyin: 'fúhé', partOfSpeech: 'v.', meaning: 'to accord with' },
          { character: '负责', pinyin: 'fùzé', partOfSpeech: 'v.', meaning: 'to be in charge of' },
          { character: '改变', pinyin: 'gǎibiàn', partOfSpeech: 'v.', meaning: 'to change' },
          { character: '感情', pinyin: 'gǎnqíng', partOfSpeech: 'n.', meaning: 'feeling' },
          { character: '顾客', pinyin: 'gùkè', partOfSpeech: 'n.', meaning: 'customer, client' },
          { character: '紧张', pinyin: 'jǐnzhāng', partOfSpeech: 'adj.', meaning: 'nervous' },
          { character: '另外', pinyin: 'lìngwài', partOfSpeech: 'conj.', meaning: 'besides, in addition' },
          { character: '律师', pinyin: 'lǜshī', partOfSpeech: 'n.', meaning: 'lawyer' },
          { character: '能力', pinyin: 'nénglì', partOfSpeech: 'n.', meaning: 'ability, competence' },
          { character: '判断', pinyin: 'pànduàn', partOfSpeech: 'v.', meaning: 'to judge, to decide' },
          { character: '其次', pinyin: 'qícì', partOfSpeech: 'pron.', meaning: 'second, next' },
          { character: '收入', pinyin: 'shōurù', partOfSpeech: 'n.', meaning: 'income' },
          { character: '提供', pinyin: 'tígōng', partOfSpeech: 'v.', meaning: 'to provide' },
          { character: '挺', pinyin: 'tǐng', partOfSpeech: 'adv.', meaning: 'quite, rather' },
          { character: '通知', pinyin: 'tōngzhī', partOfSpeech: 'v.', meaning: 'to inform' },
          { character: '信心', pinyin: 'xìnxīn', partOfSpeech: 'n.', meaning: 'confidence' },
          { character: '应聘', pinyin: 'yìngpìn', partOfSpeech: 'v.', meaning: 'to apply for a job' },
          { character: '与', pinyin: 'yǔ', partOfSpeech: 'prep.', meaning: 'with' },
          { character: '约会', pinyin: 'yuēhuì', partOfSpeech: 'v.', meaning: 'to date, to go to an appointment' },
          { character: '咱们', pinyin: 'zánmen', partOfSpeech: 'pron.', meaning: 'we, us' },
          { character: '招聘', pinyin: 'zhāopìn', partOfSpeech: 'v.', meaning: 'to recruit' },
          { character: '正式', pinyin: 'zhèngshì', partOfSpeech: 'adj.', meaning: 'formal' },
          { character: '专业', pinyin: 'zhuānyè', partOfSpeech: 'n.', meaning: 'major, specialty' },
          { character: '准时', pinyin: 'zhǔnshí', partOfSpeech: 'adj.', meaning: 'punctual, on time' },
        ],
      }
      ,
      {
        unit: 4,
        words: [
          { character: '按时', pinyin: 'ànshí', partOfSpeech: 'adv.', meaning: 'on time, on schedule' },
          { character: '按照', pinyin: 'ànzhào', partOfSpeech: 'prep.', meaning: 'according to' },
          { character: '保证', pinyin: 'bǎozhèng', partOfSpeech: 'v.', meaning: 'to guarantee' },
          { character: '不得不', pinyin: 'bù dé bù', partOfSpeech: 'v.', meaning: 'to have to, to have no choice but' },
          { character: '成功', pinyin: 'chénggōng', partOfSpeech: 'adj.', meaning: 'successful' },
          { character: '调查', pinyin: 'diàochá', partOfSpeech: 'v.', meaning: 'to survey, to investigate' },
          { character: '方法', pinyin: 'fāngfǎ', partOfSpeech: 'n.', meaning: 'method, way' },
          { character: '份', pinyin: 'fèn', partOfSpeech: 'n.', meaning: 'used for jobs among other things' },
          { character: '感谢', pinyin: 'gǎnxiè', partOfSpeech: 'v.', meaning: 'to thank' },
          { character: '工资', pinyin: 'gōngzī', partOfSpeech: 'n.', meaning: 'pay, salary' },
          { character: '积累', pinyin: 'jīlěi', partOfSpeech: 'v.', meaning: 'to accumulate' },
          { character: '计划', pinyin: 'jìhuà', partOfSpeech: 'n./v.', meaning: 'plan; to intend to' },
          { character: '奖金', pinyin: 'jiǎngjīn', partOfSpeech: 'n.', meaning: 'money award, bonus' },
          { character: '经验', pinyin: 'jīngyàn', partOfSpeech: 'n.', meaning: 'experience' },
          { character: '乱', pinyin: 'luàn', partOfSpeech: 'adj.', meaning: 'hurry-scurry, confused' },
          { character: '甚至', pinyin: 'shènzhì', partOfSpeech: 'conj.', meaning: 'even, so far as to' },
          { character: '生意', pinyin: 'shēngyì', partOfSpeech: 'n.', meaning: 'business, trade' },
          { character: '顺利', pinyin: 'shùnlì', partOfSpeech: 'adj.', meaning: 'smooth' },
          { character: '谈', pinyin: 'tán', partOfSpeech: 'v.', meaning: 'to talk, to discuss' },
          { character: '提', pinyin: 'tí', partOfSpeech: 'v.', meaning: 'to mention' },
          { character: '提前', pinyin: 'tíqián', partOfSpeech: 'v.', meaning: 'to do (sth.) in advance or ahead of time' },
          { character: '提醒', pinyin: 'tíxǐng', partOfSpeech: 'v.', meaning: 'to remind' },
          { character: '完全', pinyin: 'wánquán', partOfSpeech: 'adv.', meaning: 'completely' },
          { character: '消息', pinyin: 'xiāoxi', partOfSpeech: 'n.', meaning: 'news' },
          { character: '一切', pinyin: 'yíqiè', partOfSpeech: 'pron.', meaning: 'all, every' },
          { character: '以为', pinyin: 'yǐwéi', partOfSpeech: 'v.', meaning: 'to think, to believe' },
          { character: '原来', pinyin: 'yuánlái', partOfSpeech: 'adj.', meaning: 'original' },
          { character: '责任', pinyin: 'zérèn', partOfSpeech: 'n.', meaning: 'responsibility, duty' },
          { character: '知识', pinyin: 'zhīshi', partOfSpeech: 'n.', meaning: 'knowledge' },
          { character: '赚', pinyin: 'zhuàn', partOfSpeech: 'v.', meaning: 'to earn' },
        ],
      }
      ,{
        unit: 5,
        words: [
          { character: '标准', pinyin: 'biāozhǔn', partOfSpeech: 'n.', meaning: 'standard' },
          { character: '打折', pinyin: 'dǎ zhé', partOfSpeech: 'v.', meaning: 'to give a discount' },
          { character: '购物', pinyin: 'gòuwù', partOfSpeech: 'v.', meaning: 'to shop, to buy things' },
          { character: '光', pinyin: 'guāng', partOfSpeech: 'adv.', meaning: 'only, merely' },
          { character: '广告', pinyin: 'guǎnggào', partOfSpeech: 'n.', meaning: 'advertisement' },
          { character: '寄', pinyin: 'jì', partOfSpeech: 'v.', meaning: 'to mail, to send' },
          { character: '家具', pinyin: 'jiājù', partOfSpeech: 'n.', meaning: 'furniture' },
          { character: '价格', pinyin: 'jiàgé', partOfSpeech: 'n.', meaning: 'price' },
          { character: '考虑', pinyin: 'kǎolǜ', partOfSpeech: 'v.', meaning: 'to consider' },
          { character: '肯定', pinyin: 'kěndìng', partOfSpeech: 'adv.', meaning: 'surely, certainly' },
          { character: '浪费', pinyin: 'làngfèi', partOfSpeech: 'v.', meaning: 'to waste' },
          { character: '留', pinyin: 'liú', partOfSpeech: 'v.', meaning: 'to leave' },
          { character: '流行', pinyin: 'liúxíng', partOfSpeech: 'v.', meaning: 'to be popular' },
          { character: '年龄', pinyin: 'niánlíng', partOfSpeech: 'n.', meaning: 'age' },
          { character: '葡萄', pinyin: 'pútao', partOfSpeech: 'n.', meaning: 'grape' },
          { character: '任何', pinyin: 'rènhé', partOfSpeech: 'pron.', meaning: 'any, whatever' },
          { character: '沙发', pinyin: 'shāfā', partOfSpeech: 'n.', meaning: 'sofa' },
          { character: '实际', pinyin: 'shíjì', partOfSpeech: 'n.', meaning: 'reality' },
          { character: '实在', pinyin: 'shízài', partOfSpeech: 'adv.', meaning: 'really' },
          { character: '收到', pinyin: 'shōudào', partOfSpeech: 'v.', meaning: 'to receive' },
          { character: '顺便', pinyin: 'shùnbiàn', partOfSpeech: 'adv.', meaning: 'in passing' },
          { character: '台', pinyin: 'tái', partOfSpeech: 'm.', meaning: 'used for machines' },
          { character: '味道', pinyin: 'wèidào', partOfSpeech: 'n.', meaning: 'taste' },
          { character: '现金', pinyin: 'xiànjīn', partOfSpeech: 'n.', meaning: 'cash' },
          { character: '效果', pinyin: 'xiàoguǒ', partOfSpeech: 'n.', meaning: 'effect' },
          { character: '样子', pinyin: 'yàngzi', partOfSpeech: 'n.', meaning: 'look, appearance' },
          { character: '邀请', pinyin: 'yāoqǐng', partOfSpeech: 'v.', meaning: 'to invite' },
          { character: '艺术', pinyin: 'yìshù', partOfSpeech: 'n.', meaning: 'art' },
          { character: '优点', pinyin: 'yōudiǎn', partOfSpeech: 'n.', meaning: 'merit' },
          { character: '尤其', pinyin: 'yóuqí', partOfSpeech: 'adv.', meaning: 'especially' },
          { character: '质量', pinyin: 'zhìliàng', partOfSpeech: 'n.', meaning: 'quality' },
        ],
      }
      ,
      {
        unit: 6,
        words: [
          { character: '百分之', pinyin: 'bǎi fēn zhī', partOfSpeech: '-', meaning: 'percent' },
          { character: '倍', pinyin: 'bèi', partOfSpeech: 'm.', meaning: 'times, -fold' },
          { character: '尝', pinyin: 'cháng', partOfSpeech: 'v.', meaning: 'to taste' },
          { character: '打扰', pinyin: 'dǎrǎo', partOfSpeech: 'v.', meaning: 'to disturb, to bother' },
          { character: '方面', pinyin: 'fāngmiàn', partOfSpeech: 'n.', meaning: 'aspect' },
          { character: '各', pinyin: 'gè', partOfSpeech: 'pron.', meaning: 'various, different' },
          { character: '果汁', pinyin: 'guǒzhī', partOfSpeech: 'n.', meaning: 'fruit juice' },
          { character: '好处', pinyin: 'hǎochù', partOfSpeech: 'n.', meaning: 'benefit, advantage' },
          { character: '活动', pinyin: 'huódòng', partOfSpeech: 'n.', meaning: 'activity, event' },
          { character: '获得', pinyin: 'huòdé', partOfSpeech: 'v.', meaning: 'to get, to obtain' },
          { character: '降低', pinyin: 'jiàngdī', partOfSpeech: 'v.', meaning: 'to lower, to reduce' },
          { character: '竟然', pinyin: 'jìngrán', partOfSpeech: 'adv.', meaning: 'indicating unexpectedness' },
          { character: '举办', pinyin: 'jǔbàn', partOfSpeech: 'v.', meaning: 'to hold, to conduct' },
          { character: '举行', pinyin: 'jǔxíng', partOfSpeech: 'v.', meaning: 'to hold (a meeting, event, etc.)' },
          { character: '例如', pinyin: 'lìrú', partOfSpeech: 'v.', meaning: 'for example' },
          { character: '满', pinyin: 'mǎn', partOfSpeech: 'v.', meaning: 'to reach a quota or limit' },
          { character: '免费', pinyin: 'miǎn fèi', partOfSpeech: 'v.', meaning: 'to be free of charge' },
          { character: '内', pinyin: 'nèi', partOfSpeech: 'n.', meaning: 'in, within' },
          { character: '皮肤', pinyin: 'pífū', partOfSpeech: 'n.', meaning: 'skin' },
          { character: '其中', pinyin: 'qízhōng', partOfSpeech: 'n.', meaning: 'among (which, them, etc.)' },
          { character: '轻', pinyin: 'qīng', partOfSpeech: 'adj.', meaning: 'light, of little weight' },
          { character: '情况', pinyin: 'qíngkuàng', partOfSpeech: 'n.', meaning: 'situation, circumstances' },
          { character: '售货员', pinyin: 'shòuhuòyuán', partOfSpeech: 'n.', meaning: 'salesperson' },
          { character: '所有', pinyin: 'suǒyǒu', partOfSpeech: 'adj.', meaning: 'all' },
          { character: '袜子', pinyin: 'wàzi', partOfSpeech: 'n.', meaning: 'socks' },
          { character: '西红柿', pinyin: 'xīhóngshì', partOfSpeech: 'n.', meaning: 'tomato' },
          { character: '小说', pinyin: 'xiǎoshuō', partOfSpeech: 'n.', meaning: 'novel, fiction' },
          { character: '修理', pinyin: 'xiūlǐ', partOfSpeech: 'v.', meaning: 'to repair, to mend' },
          { character: '支持', pinyin: 'zhīchí', partOfSpeech: 'v.', meaning: 'to support' },
          { character: '值得', pinyin: 'zhídé', partOfSpeech: 'v.', meaning: 'to be worth' },
        ],
      }
      ,
      {
        unit: 7,
        words: [
          { character: '擦', pinyin: 'cā', partOfSpeech: 'v.', meaning: 'to wipe' },
          { character: '超过', pinyin: 'chāoguò', partOfSpeech: 'v.', meaning: 'to exceed, to surpass' },
          { character: '抽烟', pinyin: 'chōu yān', partOfSpeech: 'v.', meaning: 'to smoke' },
          { character: '出现', pinyin: 'chūxiàn', partOfSpeech: 'v.', meaning: 'to appear, to emerge' },
          { character: '窗户', pinyin: 'chuānghu', partOfSpeech: 'n.', meaning: 'window' },
          { character: '大夫', pinyin: 'dàifu', partOfSpeech: 'n.', meaning: 'doctor' },
          { character: '掉', pinyin: 'diào', partOfSpeech: 'v.', meaning: 'used after certain verbs, indicating the result of an action' },
          { character: '动作', pinyin: 'dòngzuò', partOfSpeech: 'n.', meaning: 'action, movement' },
          { character: '肚子', pinyin: 'dùzi', partOfSpeech: 'n.', meaning: 'belly, stomach' },
          { character: '烦恼', pinyin: 'fánnǎo', partOfSpeech: 'adj.', meaning: 'worried, vexed' },
          { character: '反对', pinyin: 'fǎnduì', partOfSpeech: 'v.', meaning: 'to oppose, to object to' },
          { character: '估计', pinyin: 'gūjì', partOfSpeech: 'v.', meaning: 'to estimate, to reckon' },
          { character: '后悔', pinyin: 'hòuhuǐ', partOfSpeech: 'v.', meaning: 'to regret' },
          { character: '减肥', pinyin: 'jiǎn féi', partOfSpeech: 'v.', meaning: 'to lose weight' },
          { character: '教授', pinyin: 'jiàoshòu', partOfSpeech: 'n.', meaning: 'professor' },
          { character: '咳嗽', pinyin: 'késòu', partOfSpeech: 'v.', meaning: 'to cough' },
          { character: '空气', pinyin: 'kōngqì', partOfSpeech: 'n.', meaning: 'air' },
          { character: '来不及', pinyin: 'láibují', partOfSpeech: 'v.', meaning: 'to have not enough time to, to be too late to' },
          { character: '气候', pinyin: 'qìhòu', partOfSpeech: 'n.', meaning: 'climate' },
          { character: '散步', pinyin: 'sàn bù', partOfSpeech: 'v.', meaning: 'to take a walk' },
          { character: '帅', pinyin: 'shuài', partOfSpeech: 'adj.', meaning: 'handsome' },
          { character: '说明', pinyin: 'shuōmíng', partOfSpeech: 'v.', meaning: 'to explain, to show' },
          { character: '辛苦', pinyin: 'xīnkǔ', partOfSpeech: 'adj.', meaning: 'hard, toilsome' },
          { character: '严重', pinyin: 'yánzhòng', partOfSpeech: 'adj.', meaning: 'serious, grave' },
          { character: '研究', pinyin: 'yánjiū', partOfSpeech: 'v.', meaning: 'to study, to do research' },
          { character: '要是', pinyin: 'yàoshi', partOfSpeech: 'conj.', meaning: 'if, supposing' },
          { character: '植物', pinyin: 'zhíwù', partOfSpeech: 'n.', meaning: 'plant' },
          { character: '指', pinyin: 'zhǐ', partOfSpeech: 'v.', meaning: 'to refer to' },
        ],
      }
      ,
      {
        unit: 8,
        words: [
          { character: '成为', pinyin: 'chéngwéi', partOfSpeech: 'v.', meaning: 'to become' },
          { character: '大使馆', pinyin: 'dàshǐguǎn', partOfSpeech: 'n.', meaning: 'embassy' },
          { character: '到处', pinyin: 'dàochù', partOfSpeech: 'adv.', meaning: 'everywhere' },
          { character: '堵车', pinyin: 'dǔchē', partOfSpeech: 'n.', meaning: 'traffic jam' },
          { character: '发生', pinyin: 'fāshēng', partOfSpeech: 'v.', meaning: 'to happen, to take place' },
          { character: '放松', pinyin: 'fàngsōng', partOfSpeech: 'v.', meaning: 'to relax' },
          { character: '回忆', pinyin: 'huíyì', partOfSpeech: 'v.', meaning: 'to call to mind, to recall' },
          { character: '怀念', pinyin: 'huáiniàn', partOfSpeech: 'v.', meaning: 'to call to mind, to recall' },
          { character: '积极', pinyin: 'jījí', partOfSpeech: 'adj.', meaning: 'positive' },
          { character: '景色', pinyin: 'jǐngsè', partOfSpeech: 'n.', meaning: 'scene, view' },
          { character: '距离', pinyin: 'jùlí', partOfSpeech: 'n.', meaning: 'distance' },
          { character: '科学', pinyin: 'kēxué', partOfSpeech: 'n.', meaning: 'science' },
          { character: '耐心', pinyin: 'nàixīn', partOfSpeech: 'n.', meaning: 'patience' },
          { character: '巧克力', pinyin: 'qiǎokèlì', partOfSpeech: 'n.', meaning: 'chocolate' },
          { character: '亲戚', pinyin: 'qīnqi', partOfSpeech: 'n.', meaning: 'relative, kinsfolk' },
          { character: '缺少', pinyin: 'quēshǎo', partOfSpeech: 'v.', meaning: 'to lack' },
          { character: '伤心', pinyin: 'shāngxīn', partOfSpeech: 'adj.', meaning: 'sad, sorrowful' },
          { character: '生命', pinyin: 'shēngmìng', partOfSpeech: 'n.', meaning: 'life' },
          { character: '师傅', pinyin: 'shīfu', partOfSpeech: 'n.', meaning: 'a polite title for one with accomplished skills in a trade or handicraft' },
          { character: '使', pinyin: 'shǐ', partOfSpeech: 'v.', meaning: 'to make, to cause' },
          { character: '态度', pinyin: 'tàidù', partOfSpeech: 'n.', meaning: 'attitude' },
          { character: '特点', pinyin: 'tèdiǎn', partOfSpeech: 'n.', meaning: 'characteristic' },
          { character: '往往', pinyin: 'wǎngwǎng', partOfSpeech: 'adv.', meaning: 'often, usually' },
          { character: '心情', pinyin: 'xīnqíng', partOfSpeech: 'n.', meaning: 'mood, state of mind' },
          { character: '压力', pinyin: 'yālì', partOfSpeech: 'n.', meaning: 'pressure, stress' },
          { character: '阳光', pinyin: 'yángguāng', partOfSpeech: 'adj.', meaning: 'optimistic, cheerful' },
          { character: '因此', pinyin: 'yīncǐ', partOfSpeech: 'conj.', meaning: 'therefore, so' },
          { character: '愉快', pinyin: 'yúkuài', partOfSpeech: 'adj.', meaning: 'glad, cheerful' },
          { character: '证明', pinyin: 'zhèngmíng', partOfSpeech: 'v.', meaning: 'to prove' },
          { character: '只要', pinyin: 'zhǐyào', partOfSpeech: 'conj.', meaning: 'as long as, provided' },
        ],
      },
      {
        unit: 9,
        words: [
          { character: '饼干', pinyin: 'bǐnggān', partOfSpeech: 'n.', meaning: 'biscuit' },
          { character: '当时', pinyin: 'dāngshí', partOfSpeech: 'adv.', meaning: 'then, at that time' },
          { character: '得', pinyin: 'děi', partOfSpeech: 'mod.', meaning: 'must, have to' },
          { character: '放弃', pinyin: 'fàngqì', partOfSpeech: 'v.', meaning: 'to give up' },
          { character: '国际', pinyin: 'guójì', partOfSpeech: 'n.', meaning: 'international' },
          { character: '过程', pinyin: 'guòchéng', partOfSpeech: 'n.', meaning: 'course, process' },
          { character: '汗', pinyin: 'hàn', partOfSpeech: 'n.', meaning: 'sweat, perspiration' },
          { character: '坚持', pinyin: 'jiānchí', partOfSpeech: 'v.', meaning: 'to insist, to persist' },
          { character: '结果', pinyin: 'jiéguǒ', partOfSpeech: 'n.', meaning: 'result' },
          { character: '经历', pinyin: 'jīnglì', partOfSpeech: 'v.', meaning: 'to go through, to experience' },
          { character: '可是', pinyin: 'kěshì', partOfSpeech: 'conj.', meaning: 'but, however' },
          { character: '理想', pinyin: 'lǐxiǎng', partOfSpeech: 'n.', meaning: 'ideal' },
          { character: '难道', pinyin: 'nándào', partOfSpeech: 'adv.', meaning: 'used in a rhetorical question for emphasis' },
          { character: '篇', pinyin: 'piān', partOfSpeech: 'm.', meaning: 'used for writings, papers or articles' },
          { character: '轻松', pinyin: 'qīngsōng', partOfSpeech: 'adj.', meaning: 'relaxed, effortless' },
          { character: '区别', pinyin: 'qūbié', partOfSpeech: 'n.', meaning: 'difference, distinction' },
          { character: '取', pinyin: 'qǔ', partOfSpeech: 'v.', meaning: 'to gain, to seek' },
          { character: '失败', pinyin: 'shībài', partOfSpeech: 'v.', meaning: 'to fail' },
          { character: '随便', pinyin: 'suíbiàn', partOfSpeech: 'adj.', meaning: 'casual, at random' },
          { character: '通过', pinyin: 'tōngguò', partOfSpeech: 'prep.', meaning: 'through, by means of' },
          { character: '网球', pinyin: 'wǎngqiú', partOfSpeech: 'n.', meaning: 'tennis' },
          { character: '许多', pinyin: 'xǔduō', partOfSpeech: 'num.', meaning: 'many, plenty of' },
          { character: '赢', pinyin: 'yíng', partOfSpeech: 'v.', meaning: 'to win' },
          { character: '勇敢', pinyin: 'yǒnggǎn', partOfSpeech: 'adj.', meaning: 'brave, courageous' },
          { character: '暂时', pinyin: 'zànshí', partOfSpeech: 'n.', meaning: 'temporary, for the time being' },
          { character: '正确', pinyin: 'zhèngquè', partOfSpeech: 'adj.', meaning: 'right, correct' },
          { character: '至少', pinyin: 'zhìshǎo', partOfSpeech: 'adv.', meaning: 'at least' },
          { character: '主意', pinyin: 'zhǔyi/zhǔyì', partOfSpeech: 'n.', meaning: 'idea, plan' },
          { character: '总结', pinyin: 'zǒngjié', partOfSpeech: 'v.', meaning: 'to sum up' },
          { character: '作家', pinyin: 'zuòjiā', partOfSpeech: 'n.', meaning: 'writer' },
        ],
      },
      {
        unit: 10,
        words: [
          { character: '比如', pinyin: 'bǐrú', partOfSpeech: 'v.', meaning: 'for example, such as' },
          { character: '不过', pinyin: 'bùguò', partOfSpeech: 'conj.', meaning: 'but, yet' },
          { character: '答案', pinyin: 'dá\'àn', partOfSpeech: 'n.', meaning: 'answer, key' },
          { character: '等', pinyin: 'děng', partOfSpeech: 'part.', meaning: 'and so on' },
          { character: '低', pinyin: 'dī', partOfSpeech: 'adj.', meaning: 'low' },
          { character: '发展', pinyin: 'fāzhǎn', partOfSpeech: 'v.', meaning: 'to develop, to promote' },
          { character: '翻译', pinyin: 'fānyì', partOfSpeech: 'n.', meaning: 'translator, interpreter' },
          { character: '方向', pinyin: 'fāngxiàng', partOfSpeech: 'n.', meaning: 'direction, orientation' },
          { character: '富', pinyin: 'fù', partOfSpeech: 'adj.', meaning: 'rich, wealthy' },
          { character: '关键', pinyin: 'guānjiàn', partOfSpeech: 'n.', meaning: 'hinge, crux' },
          { character: '建议', pinyin: 'jiànyì', partOfSpeech: 'n./v.', meaning: 'suggestion, advice; to advise' },
          { character: '将来', pinyin: 'jiānglái', partOfSpeech: 'n.', meaning: 'future' },
          { character: '经济', pinyin: 'jīngjì', partOfSpeech: 'n.', meaning: 'economy' },
          { character: '空儿', pinyin: 'kòngr', partOfSpeech: 'n.', meaning: 'free time, spare time' },
          { character: '困', pinyin: 'kùn', partOfSpeech: 'adj.', meaning: 'sleepy' },
          { character: '拉', pinyin: 'lā', partOfSpeech: 'v.', meaning: 'to pull, to drag' },
          { character: '礼拜天', pinyin: 'lǐbàitiān', partOfSpeech: 'n.', meaning: 'Sunday' },
          { character: '母亲', pinyin: 'mǔqīn', partOfSpeech: 'n.', meaning: 'mother' },
          { character: '穷', pinyin: 'qióng', partOfSpeech: 'adj.', meaning: 'poor, impoverished' },
          { character: '确实', pinyin: 'quèshí', partOfSpeech: 'adv.', meaning: 'truly, indeed' },
          { character: '硕士', pinyin: 'shuòshì', partOfSpeech: 'n.', meaning: 'Master, person who has a master’s degree' },
          { character: '糖', pinyin: 'táng', partOfSpeech: 'n.', meaning: 'sugar, candy' },
          { character: '躺', pinyin: 'tǎng', partOfSpeech: 'v.', meaning: 'to lie (on one’s back)' },
          { character: '条件', pinyin: 'tiáojiàn', partOfSpeech: 'n.', meaning: 'condition' },
          { character: '橡皮', pinyin: 'xiàngpí', partOfSpeech: 'n.', meaning: 'eraser, rubber' },
          { character: '兴奋', pinyin: 'xīngfèn', partOfSpeech: 'adj.', meaning: 'excited' },
          { character: '永远', pinyin: 'yǒngyuǎn', partOfSpeech: 'adv.', meaning: 'forever' },
          { character: '优秀', pinyin: 'yōuxiù', partOfSpeech: 'adj.', meaning: 'excellent, outstanding' },
          { character: '由于', pinyin: 'yóuyú', partOfSpeech: 'conj.', meaning: 'because, since' },
          { character: '职业', pinyin: 'zhíyè', partOfSpeech: 'n.', meaning: 'occupation, profession' },
        ],
      }
      
      
      
      
      
      
        // Add units up to Unit 20, each containing at least 50 words, to reach 1000 words
      ],
    };
